Add Angle struct
Palm-Studios/sh3redux pull request #115
Opened 2017-10-01 14:23 UTC by z33ky

This will make it explicit when we expect to deal with angles in degrees or radians.
The internal representation is in radians, since maths functions usually expect this and thus we hopefully need less conversions.

I'm not certain if `Angle::Zero()` and `Angle::Turn()` are useful.
Because equality-comparing floating-point values is tricky, I've opted into only providing an `IsExactlyZero` method. If we ever need to check the equality of angles in the future we can make up our minds on how to implement that.

As we stumble upon them we can add overloads for certain functions, e.g. `std::min` or `std::sin`, so we can just say `std::min(angleA, angleB)` instead of `Angle::FromRadians(angleA.AsRadians(), angleB.AsRadians())`.

2017-10-02 12:35 UTC, Quaker762 commented
Looks good. 

Did you want me to add some of this into the camera (in regards to the FOV etc) after we merge this?

2017-10-02 13:15 UTC, z33ky commented
Yes.

2017-10-16 13:19 UTC, Quaker762 commented
@z33ky I can't seem to compile with this. I'm getting a whole lot of 

`undefined reference to `angle<float>::angle(float)'|`
`undefined reference to `angle<double>::angle(double)'|`

2017-10-16 15:07 UTC, z33ky commented
Forgot the Code::Blocks project. Try again.

2017-10-17 06:21 UTC, Quaker762 commented
It still doesn't seem to be working. Hrrm

> Have you added any code using angle?

Nope, this is just a straight recompile with the angle class added. Perhaps there's a bug (_again_.....) with my version of g++ in regards to using `extern` with templates??

Here's the build log:

https://pastebin.com/Drz7A81c

2017-10-17 07:57 UTC, z33ky commented
What's the output of `nm obj\Debug\i686\source\SH3\angle.o|c++filt`?

2017-10-17 08:27 UTC, z33ky commented
This seems to be a known issue: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57728
I'm guessing that the empty body has the same effect as `= default;` here.
Try removing the `extern template` lines from `angle.hpp`. If that works I'll check the compiler version to conditionally use this feature or not. It's not necessary, just a compile time improvement.

2017-10-17 11:56 UTC, Quaker762 commented
> Try removing the extern template lines from angle.hpp. If that works I'll check the compiler version to conditionally use this feature or not. It's not necessary, just a compile time improvement.

This seems to have fixed it. The version of mingw g++ I have is 7.1.0 (not sure what the latest is on Linux). I should have a Linux box soon though.

2017-10-19 14:23 UTC, Quaker762 requested changes

2017-10-19 14:23 UTC, Quaker762 commented on include/SH3/angle.hpp
> +extern template struct angle<float>;
These need to be removed to prevent the gcc template compiler bug

2017-10-19 19:21 UTC, z33ky commented
Alright, try this.

2017-11-14 05:51 UTC, merged