Change 'Open()' to public
Palm-Studios/sh3redux pull request #129
Opened 2018-02-19 10:49 UTC by Quaker762

Moved the visibility of Open() to public. Certain objects in the future (maps etc) will need to have files in which the filename is determined at runtime, without forcing us to determine it at compile time.

@z33ky I had sh3 open in a debugger all day today and realised having `Open()` private is a _horrible_ idea.. I'm not sure how it'll interfere with your resource manager, but I really think we'll need raw file handles for a lot of things, considering how the actual engine treats everything.

2018-02-21 11:34 UTC, z33ky requested changes
This will not have any effect on my resource loady thingy.

2018-02-21 11:34 UTC, z33ky commented on include/SH3/arc/vfile.hpp
> +        vfile() : fpos(0), fname(""){}
Integers are initialized to 0 by default. `std::string` is initialized to the empty string by default as well.

2018-02-23 06:09 UTC, Quaker762 commented
> This will not have any effect on my resource loady thingy.

I moreso meant that the engine seems to ID every file and correlates that with an offset that is then seeked in the raw file handle. Also some files are structured _very_ strangely (as you can see in Mike's code). Though I suppose for some `scene` class we could have a bunch of the templated headers (I haven't seen the code so I don't quite know how it'll work haha :) )

2018-02-23 06:09 UTC, Quaker762 commented on include/SH3/arc/vfile.hpp
> +        vfile() : fpos(0), fname(""){}
You learn something new every day hahaha.

2018-02-23 17:23 UTC, z33ky approved these changes

2018-02-23 17:24 UTC, merged