Fixed assert problem in 'vfile.cpp'
Palm-Studios/sh3redux pull request #61
Opened 2017-01-12 09:14 UTC by Quaker762

Totally forgot that the assert error is thrown if 0 is returned from the
expression.... Ooops!

2017-01-12 09:49 UTC, z33ky commented
`fpos <= fsize` is safe, too. It'll just read nothing, but it's still sane behavior.

2017-01-12 11:25 UTC, Quaker762 commented
Okay that should do it. I've taken into account `fpos+len`, because otherwise it'll still read past the buffer.

2017-01-12 11:52 UTC, z33ky commented
Actually, this is what the `std::min()` call is for. `nbytes` is `len` capped by the amount of remaining bytes.

2017-01-12 13:02 UTC, Quaker762 commented
I completely forgot that was in there... I'll fix that ASAP.

2017-01-12 13:36 UTC, z33ky requested changes

2017-01-12 13:36 UTC, z33ky commented on source/SH3/arc/vfile.cpp
> +    if((std::size_t nbytes = std::min(len, fsize - fpos)) == len)
That should be `!= len`. Also I think this makes lines 79-82 redundant, as that case should be covered by this check.

2017-01-12 13:36 UTC, z33ky commented on source/SH3/arc/vfile.cpp
> +	{
You switched to tabs instead of spaces here.

2017-01-12 13:37 UTC, z33ky commented
Also, don't forget so squash :)

2017-01-13 12:05 UTC, Quaker762 commented on source/SH3/arc/vfile.cpp
> +	{
Whoops, I opened the file up in a different editor to write this line haha

2017-01-13 13:10 UTC, z33ky approved these changes

2017-01-13 13:11 UTC, merged