Dumping files
Palm-Studios/sh3redux pull request #67
Opened 2017-01-17 04:29 UTC by Quaker762

Added a function to dump virtual files to disk, so as to aid in reverse
engineering any file types that are currently unknown.

2017-01-18 13:35 UTC, z33ky requested changes

2017-01-18 13:35 UTC, z33ky commented on source/SH3/arc/vfile.cpp
> +    while(getline(ss, item, '/')); // Throw out all strings except the last one (our file name)
It'd be cheaper to look for the last `/` in the string (see `std::string::rfind`) and passing an iterator pair to `std::ofstream`'s constructor (`begin(fname) + pos` and `end(fname)`).

2017-01-18 13:35 UTC, z33ky commented on source/SH3/arc/vfile.cpp
> +        out_file << buffer[i];
The "streaming operators" (`<<`, `>>`) are meant for formatted data. We're dealing with binary data, so use `std::ofstream::write` instead. And you don't need to do it item by item then, you can just `write(buffer.data(), buffer.size())`.

2017-01-18 13:35 UTC, z33ky commented on source/SH3/arc/vfile.cpp
> +    std::ofstream out_file(item);
Check if opening fails.

2017-01-18 13:35 UTC, z33ky commented on source/SH3/arc/vfile.cpp
> +    if(!open || buffer.empty())
Shouldn't be just create an empty file if `buffer.empty()`? Is this an error?

2017-01-18 14:59 UTC, Quaker762 commented on source/SH3/arc/vfile.cpp
> +    if(!open || buffer.empty())
Not so much an error, it just doesn't dump anything to the disk to save a few clock cycles. I didn't really see the point of creating an empty file, though I did initially have it in.

2017-01-22 03:09 UTC, Quaker762 commented
@z33ky  I think I've just noticed a problem with how I have this set up. Some mesages may have more than one attribute, but if we change `currentAttr` during `Load()`, the old attribute will be lost. How do you think we should store all the attributes??

2017-01-22 10:24 UTC, z33ky commented
`currentAttr` is part of the other pull request #65. I'll answer there.
Could you add `msg.cpp` to the `source/CMakeLists.txt` as well?

2017-01-23 09:26 UTC, Quaker762 commented
Oops, I didn't even notice that. Is this PR ready for a merge?

2017-01-23 18:59 UTC, z33ky commented
Doesn't look like it
```$ git diff --name-only quaker/master quaker/dump
SILENT HILL 3 Redux.cbp
include/SH3/arc/vfile.hpp
include/SH3/system/msg/msg.hpp
source/SH3/arc/section.cpp
source/SH3/arc/types.cpp
source/SH3/arc/vfile.cpp
source/SH3/system/msg/msg.cpp
```

2017-01-24 00:28 UTC, Quaker762 commented
Oops, I didn't realise you meant to the dump branch, I'll do that and rebasr asap.

2017-01-24 08:38 UTC, z33ky approved these changes

2017-01-24 08:46 UTC, z33ky commented
Well that is confusing. It seems you have some changes intended for #65 in here, as was also previously the case as seen by my `git diff` output before your rebase. You should remove those commits (including of course adding `msg.cpp` to `CMakeLists.txt`) from this pull request, especially since the message stuff is still subject to change.

2017-01-24 09:16 UTC, Quaker762 commented
Okay, I really fucked that rebase up badly. I'm working on fixing it now...

2017-01-24 09:23 UTC, closed without merging

2017-01-24 09:23 UTC, Quaker762 commented
I'm deleting this branch and closing, I've fucked this up too hard.