Initial Implementation of Shader Programs
Palm-Studios/sh3redux pull request #73
Opened 2017-01-27 13:43 UTC by Quaker762

Can load, compile and link shaders from files. Currently untested (as we
don't have a GLContext working as of yet!)

@z33ky I'm going to add more to this over the next few days. We should probably start doing some GL stuff to test drawing/some other systems (like textures). Dis you want to try out fast-forwaring instead of merging this time?

2017-01-27 13:48 UTC, Quaker762 commented
Also see #74

2017-01-29 12:26 UTC, Quaker762 commented
Okay I've fixed a weird segfault. glShaderSource is a bizarre function...

2017-01-29 20:28 UTC, z33ky requested changes
Perhaps the `glDelete*` stuff should just be in the destructor of the class (even in the error case). This way resources will always be released when the `sh3_glprogram` is destroyed, be it because it couldn't be loaded or when it simply isn't needed anymore.

2017-01-29 20:28 UTC, z33ky commented on source/SH3/system/glprogram.cpp
> +    if(type == GL_VERTEX_SHADER)
There's plenty of code duplication in these branches.
For each shader type, only fname seems to be the difference.

2017-01-29 20:28 UTC, z33ky commented on source/SH3/system/glprogram.cpp
> +    source.close();
No need for that, RAII will do that.

2017-01-29 20:28 UTC, z33ky commented on source/SH3/system/glprogram.cpp
> +        glDeleteProgram(vertShader);
Should be `glDeleteShader` I think.

2017-01-29 20:50 UTC, z33ky commented on source/SH3/system/glprogram.cpp
> +    if(programID != 0)
```
if(programID == 0)
{
    //warn
    return;
}
```
?

2017-01-29 20:50 UTC, z33ky commented on source/SH3/system/glprogram.cpp
> +    glUseProgram(0); // The 'correct' way to unbind a shader, but apparently undefined?!?!
I don't have a huge issue with this, but as a fix we could use a dummy shader (and have a static class variable refer to it) that is set on `Unbind()`.
The dummy shader would either just render a solid color or an error message if we want to be fancy.

2017-01-29 20:50 UTC, z33ky commented on source/SH3/system/glprogram.cpp
>          while(!source.eof())
We could require the shader sources to have UNIX-style line endings ('\n'), in which case we can open the file in binary mode and use a `std::ostringstream` and read the whole file via `stringstream << source.rdbuf();`.
Reading the file like this is safer though.

2017-01-29 21:45 UTC, Quaker762 commented on source/SH3/system/glprogram.cpp
> +    if(type == GL_VERTEX_SHADER)
Yeah I'm getting on fixing this ASAP.

2017-01-30 08:17 UTC, Quaker762 commented on source/SH3/system/glprogram.cpp
> +        glDeleteProgram(vertShader);
Whoops haha

2017-01-30 08:30 UTC, Quaker762 commented on source/SH3/system/glprogram.cpp
> +    glUseProgram(0); // The 'correct' way to unbind a shader, but apparently undefined?!?!
Yeah that sounds like a good idea. Maybe even a checkered square like the Source engine haha.

2017-01-30 08:31 UTC, Quaker762 commented on source/SH3/system/glprogram.cpp
>          while(!source.eof())
Ahh I see. I'm using Windows, so I think the problem is stemming from the stupid `\r\n` at the end of each line. 

Why is this method safer?

2017-01-30 08:35 UTC, Quaker762 commented
Regarding `glDelete*()` calls, the OpenGL spec seems to recommend that glDeleteShader be called if compile or link fails. I've added `glDeleteShader()` and `glDeleteProgram()` calls to the destructor nonetheless.

2017-01-30 20:17 UTC, z33ky commented on source/SH3/system/glprogram.cpp
>          while(!source.eof())
Safer as in, doesn't lead to errors when using different line endings.
You should be able to switch to different line endings in your editor.

2017-01-30 20:20 UTC, z33ky requested changes

2017-01-30 20:20 UTC, z33ky commented on source/SH3/system/glprogram.cpp
>          die(&errorLog[0]);
When the string contains something looking like a format specifier, things will go wrong. Use `die("%s", ...)` instead.

2017-01-30 20:23 UTC, z33ky commented
The `glDestroy*` functions will still be called when the destructor is run. Would this be insufficient?
Also, now it will be called twice when a shader fails to compile, once in `Load()` and once in `sh3_glprogram`.

2017-01-31 08:59 UTC, Quaker762 commented
> The glDestroy* functions will still be called when the destructor is run. Would this be insufficient?

If anything, they should be destroyed right after the link is performed, as they are no longer needed and are just a waste of memory, though with the amount most people have in their system, this is probably a non-issue (though if we preload stuff it may be).

> Also, now it will be called twice when a shader fails to compile, once in Load() and once in sh3_glprogram

Will the constructor still be run if a call to `die()` is made??? I thought that was only the case if they're static/global objects. 
Also, now that I think about it, should we actually die if it fails to compile, or just replace the shader with a default one as you've suggested somewhere in the comment chain?

2017-01-31 09:00 UTC, Quaker762 commented on source/SH3/system/glprogram.cpp
>          die(&errorLog[0]);
Completely missed that, it's fixed now.

2017-01-31 09:58 UTC, z33ky commented
I though that `die()` was just a sort of "error-handling to be implemented later" in most cases.
Like stuff not being found in an arc doesn't seem to be a truly fatal error in many cases. At worst it should just abort loading the current scene, not the whole program.

2017-01-31 10:07 UTC, Quaker762 commented
> I though that die() was just a sort of "error-handling to be implemented later" in most cases.

True, we should probably just keep them to aid with debugging shaders at this point. 

> Like stuff not being found in an arc doesn't seem to be a truly fatal error in many cases

Wouldn't that imply the file is corrupt though?

Also, do you want me to move the `glDeleteShader()` calls to straight after the program has been linked, and leave just `glDeleteProgram()` in the destructor?

2017-02-02 10:46 UTC, z33ky commented
> Wouldn't that imply the file is corrupt or damaged in some way though?

That or driver issues probably.
I think we should make a best effort. If something goes wrong we should definitely log, but just fallback to the dummy shader. It probably won't make for a good playing experience, but if multiple shader fail for instance, then you get all errors in one run, instead of a cycle of run, die, fix shader until all are fixed.

Also, do you want me to move the glDeleteShader() calls to straight after the program has been linked, and leave just glDeleteProgram() in the destructor?

2017-02-02 10:54 UTC, z33ky commented
> Also, do you want me to move the `glDeleteShader()` calls to straight after the program has been linked, and leave just `glDeleteProgram()` in the destructor?

Yeah, that seems good. Although now `glDeleteShader()` is missing for the successful case.
The spec is okay with deleting the shader while still attached; It will then be deleted when the shader is detached. So we should just always do that after the shader was attached.
The program will also automatically detach the shaders, so we don't need to do that manually.

2017-02-02 12:21 UTC, Quaker762 commented
> I think we should make a best effort. If something goes wrong we should definitely log, but just fallback to the dummy shader. It probably won't make for a good playing experience, but if multiple shader fail for instance, then you get all errors in one run, instead of a cycle of run, die, fix shader until all are fixed.

Good point, I'll get rid of all of the calls to `die()` and replace them with `Log()` with the `ERROR` status.

> Yeah, that seems good. Although now glDeleteShader() is missing for the successful case.

Bloody hell, more of my 1AM programming... I think I should make myself a coffee before I attempt to program (that or crack open a beer). I've fixed it now.

> The spec is okay with deleting the shader while still attached

I had no clue this was the case. Everything I read 'recommended' a detach before delete. Very interesting. I've removed all calls to detach.

2017-02-02 13:08 UTC, z33ky commented on source/SH3/system/glprogram.cpp
> +        Log(LogLevel::ERROR, "sh3_glprogram::Compile( ): Unable to open a handle to %s!", fname.c_str());
I think we can just `return` at this point.
`//TODO: default shader fallback.`

2017-02-02 13:09 UTC, z33ky commented
You can also squash the commits. I don't see a good reason to keep them separate.

2017-02-02 13:32 UTC, z33ky commented on source/SH3/system/glprogram.cpp
> +    }
```
else
    die()
```

2017-02-02 13:32 UTC, z33ky commented on source/SH3/system/glprogram.cpp
> +#define BAD_SHADER 0
This should be a `static const GLuint` IMO.

2017-02-02 13:32 UTC, z33ky approved these changes

2017-02-02 14:34 UTC, merged