Added way to calculate Projection Matrix
Palm-Studios/sh3redux pull request #98
Opened 2017-07-14 11:58 UTC by Quaker762

Added functionality in the OpenGL context to calculate the current
Projection Matrix according to the Camera's FOV and the current Window's
dimensions, as well as being able to set the near and far values of the
current view frustum (handy for the outdoor Silent Hill level of SH3 and SH2). This may eventually need to be moved, as I don't really see a point in passing the window to any game logic (perhaps to change the Window settings in game, though this is unlike the original).

@z33ky Do you think this should be moved somewhere else?? It seems most devs put it in their 'renderer' (or in our case our context), though we could move it to the main game loop when we get further along with development.

2017-07-14 14:38 UTC, z33ky requested changes

2017-07-14 14:38 UTC, z33ky commented on include/SH3/system/glcontext.hpp
> +    class sh3_context
While we're renaming, this can be just `context`.

2017-07-14 14:38 UTC, z33ky commented on include/SH3/system/glcontext.hpp
> +        *  Calculate the projection matrix of our
"of our" ...?

2017-07-14 14:38 UTC, z33ky commented on include/SH3/system/glcontext.hpp
> +        *   @param fov - The Field Of View (FOV) of our Viewing Frustum. Defined in @ref sh3_graphics::camera
Add trailing dot.

2017-07-14 14:38 UTC, z33ky commented on include/SH3/system/window.hpp
> +    std::unique_ptr<SDL_Window, sdl_destroyer>  hwnd;       /**< Our window handle */
An additional space sneaked in.

2017-07-14 14:40 UTC, z33ky commented
> Do you think this should be moved somewhere else??

I think we should place the function in the file we need it at the moment. When we need it elsewhere, then we have additional information to decide in which module it makes sense to have the function.

2017-07-16 06:30 UTC, Quaker762 commented on include/SH3/system/glcontext.hpp
> +        *  Calculate the projection matrix of our
Whoops...

2017-07-16 06:33 UTC, Quaker762 commented
Sounds good. We need a way to pass in the projection matrix to scene, as it's required to draw models and scenes (using `gl_Position = model * view * projection` etc).

2017-07-16 08:49 UTC, z33ky requested changes

2017-07-16 08:49 UTC, z33ky commented on include/SH3/system/glcontext.hpp
> +        *  @param name - Name of
"Name of ..."

2017-07-16 08:49 UTC, z33ky commented on include/SH3/system/glcontext.hpp
> +        *  @return char* from @c glGetString
Add trailing dot.

2017-07-17 21:03 UTC, merged